// Curated directory of popular self-hosted and SaaS apps with pre-mapped icons.
// Used by the "Add App" feature so admins can search and pick instead of manual entry.

export const appDirectory = [
	// Storage & Files
	{ name: 'Immich', icon: 'si:immich', category: 'Storage', self_hosted: true },
	{ name: 'Nextcloud', icon: 'di:nextcloud', category: 'Storage', self_hosted: true },
	{ name: 'Paperless-ngx', icon: 'di:paperless-ngx', category: 'Storage', self_hosted: true },
	{ name: 'Seafile', icon: 'di:seafile', category: 'Storage', self_hosted: true },
	{ name: 'Syncthing', icon: 'di:syncthing', category: 'Storage', self_hosted: true },
	{ name: 'Filebrowser', icon: 'di:filebrowser', category: 'Storage', self_hosted: true },
	{ name: 'MinIO', icon: 'di:minio', category: 'Storage', self_hosted: true },
	{ name: 'PhotoPrism', icon: 'di:photoprism', category: 'Storage', self_hosted: true },
	{ name: 'Google Drive', icon: 'si:googledrive', category: 'Storage' },
	{ name: 'Dropbox', icon: 'si:dropbox', category: 'Storage' },
	{ name: 'OneDrive', icon: 'si:microsoftonedrive', category: 'Storage' },

	// Media
	{ name: 'Navidrome', icon: 'di:navidrome', category: 'Media', self_hosted: true },
	{ name: 'Jellyfin', icon: 'di:jellyfin', category: 'Media', self_hosted: true },
	{ name: 'Plex', icon: 'di:plex', category: 'Media', self_hosted: true },
	{ name: 'Emby', icon: 'di:emby', category: 'Media', self_hosted: true },
	{ name: 'Sonarr', icon: 'di:sonarr', category: 'Media', self_hosted: true },
	{ name: 'Radarr', icon: 'di:radarr', category: 'Media', self_hosted: true },
	{ name: 'Lidarr', icon: 'di:lidarr', category: 'Media', self_hosted: true },
	{ name: 'Prowlarr', icon: 'di:prowlarr', category: 'Media', self_hosted: true },
	{ name: 'Bazarr', icon: 'di:bazarr', category: 'Media', self_hosted: true },
	{ name: 'Overseerr', icon: 'di:overseerr', category: 'Media', self_hosted: true },
	{ name: 'Stremio', icon: 'si:stremio', category: 'Media' },
	{ name: 'YouTube', icon: 'si:youtube', category: 'Media' },
	{ name: 'Netflix', icon: 'si:netflix', category: 'Media' },
	{ name: 'Spotify', icon: 'si:spotify', category: 'Media' },
	{ name: 'Apple Music', icon: 'si:applemusic', category: 'Media' },
	{ name: 'Disney+', icon: 'si:disneyplus', category: 'Media' },
	{ name: 'Prime Video', icon: 'si:primevideo', category: 'Media' },
	{ name: 'Hotstar', icon: 'si:hotstar', category: 'Media' },

	// Security & Auth
	{ name: 'Bitwarden', icon: 'si:bitwarden', category: 'Security', self_hosted: true },
	{ name: 'Vaultwarden', icon: 'di:vaultwarden', category: 'Security', self_hosted: true },
	{ name: 'Authelia', icon: 'di:authelia', category: 'Security', self_hosted: true },
	{ name: 'Authentik', icon: 'di:authentik', category: 'Security', self_hosted: true },
	{ name: 'Keycloak', icon: 'di:keycloak', category: 'Security', self_hosted: true },
	{ name: 'LLDAP', icon: 'di:lldap', category: 'Security', self_hosted: true },
	{ name: 'Netbird', icon: 'di:netbird', category: 'Security', self_hosted: true },
	{ name: 'WireGuard', icon: 'di:wireguard', category: 'Security', self_hosted: true },
	{ name: 'Tailscale', icon: 'di:tailscale', category: 'Security', self_hosted: true },

	// Tools & Productivity
	{ name: 'Gitea', icon: 'di:gitea', category: 'Tools', self_hosted: true },
	{ name: 'Forgejo', icon: 'di:forgejo', category: 'Tools', self_hosted: true },
	{ name: 'Code Server', icon: 'di:code-server', category: 'Tools', self_hosted: true },
	{ name: 'Home Assistant', icon: 'di:home-assistant', category: 'Tools', self_hosted: true },
	{ name: 'Portainer', icon: 'di:portainer', category: 'Tools', self_hosted: true },
	{ name: 'Grafana', icon: 'di:grafana', category: 'Tools', self_hosted: true },
	{ name: 'Uptime Kuma', icon: 'di:uptime-kuma', category: 'Tools', self_hosted: true },
	{ name: 'Planka', icon: 'di:planka', category: 'Tools', self_hosted: true },
	{ name: 'Bookstack', icon: 'di:bookstack', category: 'Tools', self_hosted: true },
	{ name: 'Mealie', icon: 'di:mealie', category: 'Tools', self_hosted: true },
	{ name: 'Linkwarden', icon: 'di:linkwarden', category: 'Tools', self_hosted: true },
	{ name: 'n8n', icon: 'di:n8n', category: 'Tools', self_hosted: true },
	{ name: 'Beszel', icon: 'di:beszel', category: 'Tools', self_hosted: true },
	{ name: 'Dozzle', icon: 'di:dozzle', category: 'Tools', self_hosted: true },
	{ name: 'Traefik', icon: 'di:traefik', category: 'Tools', self_hosted: true },
	{ name: 'Nginx Proxy Manager', icon: 'di:nginx-proxy-manager', category: 'Tools', self_hosted: true },
	{ name: 'Pi-hole', icon: 'di:pi-hole', category: 'Tools', self_hosted: true },
	{ name: 'AdGuard Home', icon: 'di:adguard-home', category: 'Tools', self_hosted: true },
	{ name: 'Homarr', icon: 'di:homarr', category: 'Tools', self_hosted: true },
	{ name: 'Homepage', icon: 'di:homepage', category: 'Tools', self_hosted: true },
	{ name: 'Dashy', icon: 'di:dashy', category: 'Tools', self_hosted: true },

	// Communication
	{ name: 'Matrix', icon: 'si:matrix', category: 'Social', self_hosted: true },
	{ name: 'Rocket.Chat', icon: 'si:rocketdotchat', category: 'Social', self_hosted: true },

	// Social & SaaS
	{ name: 'GitHub', icon: 'si:github', category: 'Tools' },
	{ name: 'GitLab', icon: 'si:gitlab', category: 'Tools' },
	{ name: 'Claude', icon: 'si:claude', category: 'Tools' },
	{ name: 'ChatGPT', icon: 'si:openai', category: 'Tools' },
	{ name: 'Notion', icon: 'si:notion', category: 'Tools' },
	{ name: 'Figma', icon: 'si:figma', category: 'Tools' },
	{ name: 'Reddit', icon: 'si:reddit', category: 'Social' },
	{ name: 'Instagram', icon: 'si:instagram', category: 'Social' },
	{ name: 'X', icon: 'si:x', category: 'Social' },
	{ name: 'WhatsApp', icon: 'si:whatsapp', category: 'Social' },
	{ name: 'Telegram', icon: 'si:telegram', category: 'Social' },
	{ name: 'Discord', icon: 'si:discord', category: 'Social' },
	{ name: 'LinkedIn', icon: 'si:linkedin', category: 'Social' },
	{ name: 'Threads', icon: 'si:threads', category: 'Social' },
	{ name: 'Proton Mail', icon: 'si:protonmail', category: 'Social' },
	{ name: 'Gmail', icon: 'si:gmail', category: 'Social' },

	// Shopping
	{ name: 'Amazon', icon: 'di:amazon', category: 'Shopping' },
];
